# Generated by Django 5.0.1 on 2024-02-14 17:57

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_desc', tinymce.models.HTMLField()),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
                ('blog_image', models.FileField(default=None, max_length=250, null=True, upload_to='blog/')),
            ],
        ),
    ]
