# Generated by Django 5.0.1 on 2024-02-09 02:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_member',
            name='service_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
