# Generated by Django 5.0.1 on 2024-02-19 12:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_member_service_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_member',
            old_name='service_des',
            new_name='service_desc',
        ),
        migrations.RenameField(
            model_name='service_member',
            old_name='first_name',
            new_name='service_title',
        ),
        migrations.RemoveField(
            model_name='service_member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='service_member',
            name='service_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service_member',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
    ]
