# Generated by Django 5.0.1 on 2024-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_service_des_service_member_service_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_member',
            old_name='service_image',
            new_name='service_pdf',
        ),
        migrations.AlterField(
            model_name='service_member',
            name='service_title',
            field=models.CharField(max_length=500),
        ),
    ]
