# Generated by Django 5.0.1 on 2024-02-25 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveregistration',
            name='appodate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
